services:
  redis-unbound-exporter_restarter:
    image: docker:cli
    container_name: redis-unbound-exporter_restarter
    hostname: redis-unbound-exporter_restarter
    network_mode: none
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock" ]
    command:
      - /bin/sh
      - -c
      - |
        while true; do
          sleep 30

          errors=$$(docker logs --since 35s redis-unbound-exporter 2>&1 | grep -c "Couldn't connect to redis instance")

          if [ "$$errors" -ge 1 ]; then
            echo "$$(date '+%Y-%m-%d %H:%M:%S') - [ERROR] Detetados $$errors erros no redis-unbound-exporter"
            echo "$$(date '+%Y-%m-%d %H:%M:%S') - [RESTART] A reiniciar redis-unbound-exporter..."
            docker restart redis-unbound-exporter
            sleep 60
          fi
        done
    restart: unless-stopped
